// AUTO-GENERATED by scripts/convert-confessions.mjs — do not edit by hand.
// Source: app-irb-confessions (Three Forms of Unity, pt-BR).

export interface DortArticle {
  head: string
  number: number
  title: string
  paragraphs: string[]
  refs: string
}

export const DORT_ARTICLES: DortArticle[] = [
  {
    head: "I",
    number: 1,
    title: "Toda a humanidade é condenável diante de Deus",
    paragraphs: [
      'Como todos os homens pecaram em Adão, estão debaixo da maldição e merecem a morte eterna, Deus não teria feito injustiça a ninguém se tivesse resolvido deixar toda a raça humana no pecado e debaixo da maldição, e condená-la por causa do seu pecado, de acordo com estas palavras do apóstolo: "para que se cale toda boca, e todo o mundo seja culpável perante Deus … pois todos pecaram e carecem da glória de Deus" (Rm 3.19, 23) e "o salário do pecado é a morte" (Rm 6.23).',
    ],
    refs: "Rm 5.12; Rm 3.19, 23; Rm 6.23",
  },
  {
    head: "I",
    number: 2,
    title: "O envio do Filho de Deus",
    paragraphs: [
      'Mas nisso se manifestou o amor de Deus, em que Ele enviou ao mundo o Seu Filho Unigênito, "para que todo aquele que nEle crê não pereça, mas tenha a vida eterna".',
    ],
    refs: "1Jo 4.9; Jo 3.16",
  },
  {
    head: "I",
    number: 3,
    title: "A pregação do Evangelho",
    paragraphs: [
      'Assim, para que os homens sejam conduzidos à fé, Deus misericordiosamente enviou arautos da mais bem-aventurada mensagem a quem Ele quer e quando Ele quer. Pelo ministério deles os homens são chamados ao arrependimento e à fé no Cristo crucificado. Pois, "Como, porém, invocarão Aquele em quem não creram? E como crerão nAquele de quem nada ouviram? E como ouvirão, se não há quem pregue? E como pregarão, se não forem enviados?".',
    ],
    refs: "Is 52.7; 1Co 1.23, 24; Rm 10.14, 15",
  },
  {
    head: "I",
    number: 4,
    title: "Um duplo resultado",
    paragraphs: [
      "A ira de Deus permanece sobre os que não creem neste Evangelho. Mas aqueles que o recebem e abraçam a Jesus o Salvador com uma fé verdadeira e viva são libertados por Ele da ira de Deus e da destruição, e presenteados com a vida eterna.",
    ],
    refs: "Jo 3.36; Mc 16.16; Rm 10.9",
  },
  {
    head: "I",
    number: 5,
    title: "A causa da incredulidade e a fonte da fé",
    paragraphs: [
      'A causa ou a culpa dessa incredulidade, assim como a de todos os outros pecados, não está em Deus de modo nenhum, mas antes, no homem. No entanto, a fé em Jesus Cristo e a salvação através dEle é a livre dádiva de Deus, como está escrito: "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus". Semelhantemente, "Porque vos foi concedida a graça … de crerdes nEle".',
    ],
    refs: "Hb 4.6; Ef 2.8; Fp 1.29",
  },
  {
    head: "I",
    number: 6,
    title: "O decreto eterno de Deus",
    paragraphs: [
      'Procede do decreto eterno de Deus conceder, no tempo devido, o dom da fé a alguns e não a outros. Pois Ele conhece todas as Suas obras desde a eternidade, e "faz todas as coisas conforme o conselho da sua vontade". De acordo com este decreto, Ele graciosamente quebranta os corações dos eleitos, por mais duros que sejam, e os inclina a crer; entretanto, segundo o Seu justo juízo, ele deixa os não-eleitos em sua própria malignidade e dureza. E aqui, especialmente, nos é revelada a profunda, misericordiosa e ao mesmo tempo justa distinção entre homens igualmente merecedores de condenação, que é o decreto da eleição e da reprovação, revelado na Palavra de Deus. Embora os homens perversos, impuros e volúveis o distorçam para a própria destruição deles, esse mesmo decreto proporciona consolação indizível às almas santas e tementes a Deus.',
    ],
    refs: "At 13.48; 1Pe 2.8; Ef 1.11",
  },
  {
    head: "I",
    number: 7,
    title: "Definição da Eleição",
    paragraphs: [
      'A eleição é o propósito imutável de Deus pelo qual Ele, antes da fundação do mundo, segundo o soberano beneplácito da Sua vontade e por pura graça, escolheu para a salvação em Cristo de entre toda a raça humana, caída pela própria culpa do estado original de integridade no pecado e na perdição - um número definido de pessoas específicas, em nada melhores nem mais dignas que as outras, porém envolvidas na mesma miséria dos demais. Também desde a eternidade, Ele constituiu a Cristo como o Mediador e o Cabeça de todos os eleitos e o fundamento da salvação. Assim decretou dar a Cristo os que haveriam de ser salvos e chamá-los e trazêlos eficazmente à Sua comunhão pela Sua Palavra e Espírito. Ele decretou conceder-lhes a fé verdadeira em Cristo, os justificar, os santificar e por fim - depois de os ter preservado poderosamente na comunhão do Seu Filho - os glorificar, para a demonstração da Sua misericórdia e o louvor da riqueza da Sua graça gloriosa. Como está escrito: Deus nos escolheu em Cristo "antes da fundação do mundo, para sermos santos e irrepreensíveis perante ele; e em amor nos predestinou para ele, para a adoção de filhos, por meio de Jesus Cristo, segundo o beneplácito de sua vontade, para louvor da glória de sua graça, que ele nos concedeu gratuitamente no Amado". E em outro lugar: "E aos que predestinou, a esses também chamou; e aos que chamou, a esses também justificou; e aos que justificou, a esses também glorificou".',
    ],
    refs: "Ef 1.4,11; Jo 17.2, 12, 14; Jo 6.37, 44; 1Co 1.9; Ef 1.4-6; Rm 8.30",
  },
  {
    head: "I",
    number: 8,
    title: "Um único decreto de eleição",
    paragraphs: [
      "Não há vários decretos de eleição, mas um único e mesmo decreto para todos os que hão de ser salvos, tanto debaixo do Velho quanto do Novo Testamento. Porque a Escritura declara que o beneplácito, o propósito e o conselho da vontade de Deus é único. Segundo este propósito Ele nos escolheu desde a eternidade tanto para a graça quanto para a glória, tanto para a salvação e para o caminho da salvação - o qual preparou para que andássemos nele.",
    ],
    refs: "Dt 7.7; 9.6; Ef 1.4, 5; 2.10",
  },
  {
    head: "I",
    number: 9,
    title: "A eleição não se baseia em fé prevista",
    paragraphs: [
      'Tal eleição não se baseia em fé prevista, em obediência da fé, santidade ou de qualquer outra boa qualidade ou disposição que seja a causa ou a condição necessária aos homens para serem eleitos; os homens, todavia, são eleitos para a fé, para a obediência da fé, para a santidade etc. A eleição é, portanto, a fonte de todas as virtudes salvadoras de onde emana a fé, a santidade e os outros dons salvadores, e por fim a própria vida eterna, como frutos e efeitos da eleição. É isso o que o apóstolo ensina quando diz: "assim como nos escolheu nele antes da fundação do mundo, (não porque fôssemos santos, mas) para sermos santos e irrepreensíveis perante ele".',
    ],
    refs: "Rm 8.30; Ef 1.4",
  },
  {
    head: "I",
    number: 10,
    title: "A eleição baseia-se no beneplácito de Deus",
    paragraphs: [
      'A causa dessa eleição graciosa é tão-somente o beneplácito de Deus, o qual não consiste de haver Deus escolhido de entre todas as condições possíveis umas certas qualidades ou ações dos homens como requisito para a salvação; mas consiste em que Ele, de entre a multidão dos pecadores, adotou para Sua possessão certas pessoas. Pois está escrito: "ainda não eram os gêmeos nascidos, nem tinham praticado o bem ou o mal … e já fora dito a ela (a Rebeca) : O mais velho será servo do mais moço". E também: "todavia, amei a Jacó, porém aborreci a Esaú". E ainda: "e creram todos os que haviam sido destinados para a vida eterna".',
    ],
    refs: "Rm 9.11-13; Gn 25.23; Ml 1.2, 3; At 13.48",
  },
  {
    head: "I",
    number: 11,
    title: "A eleição é imutável",
    paragraphs: [
      "Como o próprio Deus é infinitamente sábio, imutável, onisciente e onipotente, assim também a Sua eleição não pode ser desfeita, refeita, alterada, revogada nem anulada; tampouco podem os eleitos ser rejeitados, nem o número deles diminuído.",
    ],
    refs: "Jo 6.37; 10.28",
  },
  {
    head: "I",
    number: 12,
    title: "A certeza da eleição",
    paragraphs: [
      "Os eleitos recebem no tempo oportuno - ainda que em vários graus e diferentes modos - a certeza da sua eterna e imutável eleição para a salvação. Eles, todavia, não a obtêm quando curiosamente investigam as coisas ocultas e profundas de Deus, mas quando observam em si mesmos, com alegria espiritual e santo deleite, os infalíveis frutos da eleição indicados na Palavra de Deus - como a fé verdadeira em Cristo, o temor filial a Deus, a piedosa tristeza pelos seus pecados, e a fome e a sede de justiça.",
    ],
    refs: "Dt 29.29; 1Co 2.10, 11; 2Co 13.5; 7.10; Mt 5.6",
  },
  {
    head: "I",
    number: 13,
    title: "O valor desta certeza",
    paragraphs: [
      "A consciência e a certeza da eleição fornecem aos filhos de Deus maior motivo para se humilharem diariamente diante dEle, para adorarem a profundidade das Suas misericórdias, para se purificarem e para amarem fervorosamente Àquele que os amou primeiro de modo tão grandioso. Contudo absolutamente não é verdade que a doutrina da eleição e o meditar nela os façam relaxar na observação dos mandamentos de Deus ou os rendam falsamente seguros. No justo juízo de Deus isso normalmente ocorre aos que supõem atrevidamente ter a graça da eleição, ou que dela falam de modo leviano e jactancioso, mas que se recusam a andar nos caminhos dos eleitos.",
    ],
    refs: "1Jo 3.3; 4.19",
  },
  {
    head: "I",
    number: 14,
    title: "Como se deve ensinar a eleição",
    paragraphs: [
      "A doutrina da eleição divina, segundo o mui sábio conselho de Deus, foi pregada pelos profetas, pelo próprio Cristo e pelos apóstolos, tanto debaixo do Velho Testamento quanto do Novo Testamento, sendo então registrada por escrito nas Sagradas Escrituras. Assim, também hoje, essa doutrina deve ser ensinada na igreja de Deus - para qual ela foi particularmente destinada - em tempo e lugar apropriados, com espírito criterioso, de modo reverente e santo, sem curiosa investigação nos caminhos do Altíssimo, para a glória do santíssimo nome de Deus, e para a viva consolação do Seu povo.",
    ],
    refs: "At 20.27; Jó 36.23-26; Rm 11.33; 12.3; 1Co 4.6",
  },
  {
    head: "I",
    number: 15,
    title: "A descrição da reprovação",
    paragraphs: [
      "As Sagradas Escrituras mostram e nos recomendam esta graça eterna e imerecida da nossa eleição, especialmente quando além disso declara que nem todos os homens são eleitos, mas que alguns não são eleitos, ou foram preteridos na eleição eterna de Deus. Deus, pelo seu beneplácito mui soberano, justo, irrepreensível e imutável, decretou deixá-los na miséria comum em que eles se lançaram por sua própria culpa e não lhes concedeu a fé salvadora, nem a graça da conversão. Para mostrar a Sua justiça, Deus os deixou em seus próprios caminhos e debaixo do Seu justo juízo, decretando, por fim, os condenar e punir eternamente, não apenas pela incredulidade deles, mas também por causa de todos os seus outros pecados. Este é o decreto da reprovação, o qual não faz de Deus o autor do pecado (o só pensar isso é blasfêmia!), antes o revela como o terrível, irrepreensível e justo Juiz e Vingador do pecado.",
    ],
    refs: "At 14.16",
  },
  {
    head: "I",
    number: 16,
    title: "Como reagir à doutrina da reprovação",
    paragraphs: [
      "Alguns ainda não discernem claramente em si mesmos uma fé viva em Cristo, nem confiança firme no coração, nem boa consciência, nem zelo pela obediência filial e pela glorificação de Deus por meio de Cristo. Apesar disso, eles usam os meios pelos quais Deus prometeu operar tais coisas em nós. Eles não devem se assustar quando se fala da reprovação, nem devem se incluir entre os reprovados. Pelo contrário, devem continuar a usar esses meios com diligência, a almejar com fervor um tempo de graça mais abundante e a esperá-lo com reverência e humildade. Há também outros que desejam se converter a Deus com seriedade, tão somente para O agradar e para serem libertos do corpo da morte, contudo não conseguem chegar até onde gostariam no caminho da piedade e da fé. Essas pessoas não deveriam ter tanto medo da doutrina da reprovação, pois Deus, que é misericordioso, prometeu que não esmagará a cana quebrada e não apagará o pavil que fumega. Há ainda outros que desprezam a Deus e ao Senhor Jesus Cristo e que se entregam completamente aos cuidados do mundo e às concupiscências da carne. Para esses, a doutrina da reprovação é mesmo apavorante, pois não se voltam para Deus com seriedade.",
    ],
    refs: "Tg 2.26; 2Co 1.12; Rm 5.11; Fp 3.3; Rm 7.24; Is 42.3; Mt 12.20; 13.22; Hb 12.29",
  },
  {
    head: "I",
    number: 17,
    title: "Os filhos de crentes que morrem na infância",
    paragraphs: [
      "Devemos julgar a respeito da vontade de Deus com base na Sua Palavra, que declara que os filhos dos crentes são santos, não por natureza, mas em virtude da aliança da graça da qual participam juntamente com os seus pais. Por essa causa, pais tementes a Deus não devem duvidar da eleição e da salvação daqueles seus filhos a quem Deus chamou desta vida ainda na infância.",
    ],
    refs: "Gn 17.7; Is 59.21; At 2.39; 1Co 7.14",
  },
  {
    head: "I",
    number: 18,
    title: "Não protesto, mas sim adoração",
    paragraphs: [
      'Aos que se queixam da graça da eleição imerecida e da severidade da reprovação justa, replicamos com as palavras do apóstolo: "Quem és tu, ó homem, para discutires com Deus?!", e com essas palavras do nosso Salvador: "Porventura, não me é lícito fazer o que quero do que é meu?". Nós, porém, adorando com reverência estes mistérios, exclamamos com o apóstolo: "Ó profundidade da riqueza, tanto da sabedoria como do conhecimento de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos! Quem, pois, conheceu a mente do Senhor? Ou quem foi o seu conselheiro? Ou quem primeiro deu a ele para que lhe venha a ser restituído? Porque dele, e por meio dele, e para ele são todas as coisas. A ele, pois, a glória eternamente. Amém!".',
    ],
    refs: "Jó 34.34-37; Rm 9.20; Mt 20.15; Rm 11.33-36",
  },
  {
    head: "II",
    number: 1,
    title: "O castigo que a justiça de Deus exige",
    paragraphs: [
      "Deus não é apenas supremamente misericordioso, mas também é supremamente justo. E conforme Ele mesmo revelou em Sua Palavra, a Sua justiça exige que os nossos pecados, cometidos contra a Sua infinita majestade, sejam castigados não apenas nessa era, mas também na era porvir, tanto no corpo quanto na alma. Não podemos escapar desse castigo se a justiça de Deus não for satisfeita.",
    ],
    refs: "Êx 34.6, 7; Rm 5.16; Gl 3.10",
  },
  {
    head: "II",
    number: 2,
    title: "A satisfação cumprida por Cristo",
    paragraphs: [
      "Nós, contudo, não podemos cumprir essa satisfação e nos livrar por nós mesmos da ira de Deus. Por isso Deus, em Sua infinita misericórdia nos deu o Seu filho unigênito como o nosso fiador. Por nós ou em nosso lugar Ele foi feito pecado e maldito na cruz para que pudesse, em nosso favor, satisfazer a Deus.",
    ],
    refs: "Rm 5.8; 2Co 5.21; Gl 3.13",
  },
  {
    head: "II",
    number: 3,
    title: "O valor infinito da morte de Cristo",
    paragraphs: [
      "A morte do Filho de Deus é o único e o mais perfeito sacrifício e satisfação pelos pecados; tem valor e mérito infinitos; é abundante o suficiente para expiar os pecados do mundo inteiro.",
    ],
    refs: "Hb 9.26, 28; 10.14; 1Jo 2.2",
  },
  {
    head: "II",
    number: 4,
    title: "Por que a Sua morte tem valor infinito",
    paragraphs: [
      "A morte do Filho de Deus tem tão grande valor e mérito porque Aquele que se submeteu a ela não é apenas o homem perfeito e verdadeiro, mas é também o filho unigênito de Deus, da mesma essência eterna e infinita com o Pai e o Espírito Santo. O nosso Salvador tinha que ter tais qualificações. Além disso, essa morte tem tão grande valor e mérito porque foi acompanhada da consciência da ira e da maldição de Deus que, pelos nossos pecados, somos merecedores.",
    ],
    refs: "Hb 4.15; 7.26; 1Jo 4.9; Mt 27.46",
  },
  {
    head: "II",
    number: 5,
    title: "A proclamação universal do evangelho",
    paragraphs: [
      "A promessa do evangelho é que todo aquele que crer em Cristo crucificado não perecerá, mas tem a vida eterna. Esta promessa deve ser anunciada e proclamada universalmente sem nenhuma discriminação a todos os povos e homens, aos quais Deus em Seu beneplácito envia o evangelho juntamente com o mandamento de que se arrependam e creiam.",
    ],
    refs: "Jo 3.16; 1Co 1.23; Mt 28.19; At 2.38; 16.31",
  },
  {
    head: "II",
    number: 6,
    title: "Por que alguns não creem",
    paragraphs: [
      "No entanto, muitos dos que foram chamados pelo evangelho não se arrependem nem creem em Cristo mas perecem na incredulidade. Isso não decorre por haver alguma defeito ou insuficiência no sacrifício de Cristo na cruz, mas pela própria culpa deles.",
    ],
    refs: "Mt 22.14; Sl 95.11; Hb 4.6",
  },
  {
    head: "II",
    number: 7,
    title: "Por que outros creem",
    paragraphs: [
      "Mas aqueles que verdadeiramente creem e pela morte de Cristo são libertos e salvos dos seus pecados e da perdição, recebem esse benefício apenas por causa da graça de Deus que lhes é dada em Cristo, desde a eternidade. Deus não deve tal graça a ninguém.",
    ],
    refs: "2Co 5.18; Ef 2.8, 9",
  },
  {
    head: "II",
    number: 8,
    title: "A eficácia da morte de Cristo",
    paragraphs: [
      "Pois este foi o soberano conselho de Deus o Pai que a eficácia salvadora e vivificante da preciosíssima morte do Seu Filho se estendesse a todos os eleitos. Foi da Sua graciosíssima vontade e intento conceder a fé justificadora apenas a eles e assim trazer-lhes infalivelmente a salvação. Isto é: Quis Deus que Cristo pelo sangue da cruz (pelo qual Ele confirmou a nova aliança) redimisse eficazmente de todo povo, tribo, nação e língua todos aqueles - e somente aqueles - que desde a eternidade foram eleitos para a salvação e Lhe foram dados pelo Pai. Ainda quis Deus que Cristo lhes desse a fé, a qual, juntamente com outros dons salvadores do Espírito Santo, Ele lhes adquiriu pela Sua morte, para que pelo Seu sangue pudesse purificá-los de todos os seus pecados - tanto do pecado original quanto dos pecados reais cometidos antes e depois da fé - e para os guardar fielmente até o fim e finalmente os apresentar a Si mesmo em glória sem nenhuma mácula ou ruga.",
    ],
    refs: "Jo 17.9; Ef 5.25-27; Lc 22.20; Hb 8.6; Ap 5.9; Fp 1.29; 1Jo 1.7; Jn 10.28; Ef 5.27",
  },
  {
    head: "II",
    number: 9,
    title: "O cumprimento do conselho de Deus",
    paragraphs: [
      'Esse conselho, que procede do amor eterno de Deus pelos eleitos, tem sido poderosamente cumprido desde a fundação do mundo até o momento presente, e continuará ainda a ser cumprido, ainda que as "portas do inferno" tentem frustrá-lo inutilmente. No tempo oportuno os eleitos serão ajuntados em uma união, e sempre existirá uma igreja de crentes fundada no sangue de Cristo. Essa igreja amá-Lo-á firmemente e servi-Lo-á fielmente como seu salvador (o qual como noivo derramou a Sua vida na cruz pela Sua noiva) e celebrará os seus louvores aqui e por toda a eternidade.',
    ],
    refs: "Mt 16.18; Jo 11.52; 1Rs 19.18; Ef 5.25",
  },
  {
    head: "III/IV",
    number: 1,
    title: "O resultado da queda",
    paragraphs: [
      "No princípio o homem foi criado à imagem de Deus. Foi adornado em seu entendimento com o verdadeiro e total conhecimento do Seu criador e de todas as coisas espirituais. A sua vontade e o seu coração eram retos; todos os seus sentimentos, puros; o homem era, portanto, completamente santo. Mas ao rebelar-se contra Deus pela instigação do diabo e pelo próprio livre-arbítrio, ele se privou desses dons excelentes e em lugar deles trouxe sobre si cegueira, trevas terríveis; vão e perverso juízo em sua mente; malignidade, rebelião e obstinação em sua vontade e coração; além de impureza em todos os seus sentimentos.",
    ],
    refs: "Gn 1.26, 27; Gn 3.1-7; Ef 4.17-19",
  },
  {
    head: "III/IV",
    number: 2,
    title: "A propagação da corrupção",
    paragraphs: [
      "Depois da queda o homem se tornou corrompido e, como pai corrompido, gerou filhos corrompidos. Assim a corrupção, de acordo com o justo juízo de Deus, propagou-se de Adão a todos os seus descendentes à exceção de Cristo somente - não por imitação, como afirmavam os antigos pelagianos, mas pela propagação de uma natureza pervertida.",
    ],
    refs: "Jó 14.4; Sl 51.7; Rm 5.12; Hb 4.15",
  },
  {
    head: "III/IV",
    number: 3,
    title: "A total incapacidade do homem",
    paragraphs: [
      "Portanto todos os homens são concebidos em pecado e nascem como filhos da ira, incapazes de qualquer bem salvador, inclinados para o mal, mortos em pecados e escravos do pecado. Sem a graça do Espírito Santo regenerador não desejam nem poderão retornar a Deus, nem corrigir a sua natureza depravada ou se preparar para essa correção.",
    ],
    refs: "Ef 2.1, 3; Jo 8.34; Rm 6.16, 17; Jo 3.3-6; Tt 3.5",
  },
  {
    head: "III/IV",
    number: 4,
    title: "A insuficiência da luz da natureza",
    paragraphs: [
      "É certo que depois da queda restou no homem um pouco da luz natural pela qual ainda lhe ficou alguma noção de Deus, das coisas naturais, da diferença entre o honrável e o vergonhoso, e dá mostras de alguma consideração pela virtude e pela ordem exterior. Mas está tão longe de chegar ao conhecimento salvador de Deus e da verdadeira conversão por meio dessa luz da natureza que nem mesmo a usa do modo apropriado nas questões naturais e civis. Antes, não importa o que seja esta luz, o homem a polui completamente de várias formas e a suprime pela sua injustiça, tornando-se assim inescusável diante de Deus.",
    ],
    refs: "Rm 1.19, 20; 2.14, 15; 1.18, 20",
  },
  {
    head: "III/IV",
    number: 5,
    title: "A insuficiência da lei",
    paragraphs: [
      "Aquilo que se afirma da luz da natureza também é válido para os Dez Mandamentos dados por Deus através de Moisés, particularmente aos judeus. Embora a lei revele a grandeza do pecado e convença cada vez mais o homem da sua culpa, ainda assim não lhe aponta a cura nem lhe dá poder para se erguer e sair das suas misérias. Antes, enfraquecida pela carne, a lei deixa o transgressor debaixo de maldição. Por essa causa, o homem não pode obter a graça salvadora através da lei.",
    ],
    refs: "Rm 3.19, 20; 7:10.13; 8.3; 2Co 3.6, 7",
  },
  {
    head: "III/IV",
    number: 6,
    title: "A necessidade do evangelho",
    paragraphs: [
      "Portanto, aquilo que nem a luz da natureza nem a lei pode fazer, Deus realiza pelo poder do Espírito Santo através da palavra ou ministério da reconciliação: o evangelho do Messias, pelo qual agradou a Deus salvar aos que creem tanto na antiga quanto da nova dispensação.",
    ],
    refs: "2Co 5.18, 19; 1Co 1.21",
  },
  {
    head: "III/IV",
    number: 7,
    title: "Por que o evangelho é enviado a uns e não a outros",
    paragraphs: [
      "Na velha dispensação Deus revelou a uns poucos esse mistério da Sua vontade. Na nova dispensação, no entanto, Ele não considerou os povos de modo diferente e o revelou a um número muito maior de pessoas. Não se deve atribuir a causa dessa distribuição do evangelho ao mérito de um povo sobre o outro, nem ao melhor uso da luz da natureza, mas ao beneplácito soberano e ao amor imerecido de Deus. Por essa causa, nós, a quem se concedeu uma tão grande graça, superior e contrária a tudo o que merecemos, devemos reconhecê-la de coração humilde e grato. Mas, quanto àqueles a quem tal graça não é dada, devemos adorar com o apóstolo a severidade e a justiça dos juízos de Deus, sem de modo algum investigá-los inquisitiva e curiosamente.",
    ],
    refs: "Ef 1.9; 2:14; Cl 3.11; Rm 2.11; Mt 11.26; Rm 11.22, 23; Ap 16.7; Dt 29.29",
  },
  {
    head: "III/IV",
    number: 8,
    title: "A sincera chamada do Evangelho",
    paragraphs: [
      "Tantos quantos são chamados pelo Evangelho, sinceramente o são, pois Deus séria e sinceramente revela em Sua Palavra aquilo que lhe agrada, a saber: que todos os que são chamados venham a Ele. Ele também promete verdadeiramente o descanso para as suas almas e a vida eterna a todo o que a Ele vierem e crerem.",
    ],
    refs: "Is 55.1; Mt 22.4; Ap 22.17; Jo 6.37; Mt 11.28, 29",
  },
  {
    head: "III/IV",
    number: 9,
    title: "Por que alguns dos que são chamados não vêm",
    paragraphs: [
      "Não é culpa do Evangelho - nem do Cristo oferecido pelo Evangelho, nem de Deus, que os chama pelo Evangelho e quem até mesmo lhes concede vários dons - que muitos dos que são chamados pelo ministério do Evangelho não vêm nem são convertidos. A culpa está neles mesmos. Alguns deles não se importam com a palavra da vida nem a aceitam. Outros de fato a recebem, mas não a aceitam em seus corações, e logo retrocedem depois que desaparece a alegria de uma fé temporária. Há ainda daqueles que sufocam a semente da Palavra com os espinhos dos cuidados e dos prazeres desse mundo e que não produzem nenhum fruto. É esse o ensino do nosso Salvador na parábola da semeadura em Mateus 13.",
    ],
    refs: "Mt 11.20-24; 22:1-8; 23:37",
  },
  {
    head: "III/IV",
    number: 10,
    title: "Por que outros que são chamados vêm",
    paragraphs: [
      "Outros que são chamados pelo ministério do Evangelho vêm e são convertidos. Não se deve atribuir isso ao homem, como se ele, por causa do seu livre-arbítrio, fosse superior àqueles que receberam graça igual ou suficiente para a fé ou conversão (como afirma a arrogante heresia de Pelágio). Deve-se atribuir isso a Deus, pois foi Ele quem escolheu os Seus em Cristo desde a eternidade e os chama eficazmente no tempo; concede-lhes a fé e o arrependimento; livra-os do poder das trevas e os transfere para o reino do Seu Filho. Tudo isso Ele faz para que eles possam declarar os maravilhosos feitos dAquele que os chamou das trevas para a Sua maravilhosa luz, e para que não se gloriem em si mesmos, mas no Senhor - segundo o testemunho dos apóstolos em diversas partes da Escritura.",
    ],
    refs: "Rm 9.16; Cl 1.13; Gl 1.4; 1Pe 2.9; 1Co 1.31; 2Co 10.17; Ef 2.8, 9",
  },
  {
    head: "III/IV",
    number: 11,
    title: "Como Deus realiza a conversão",
    paragraphs: [
      "Deus realiza o Seu beneplácito nos eleitos e opera neles a verdadeira conversão da seguinte maneira: Ele cuida para que o evangelho lhes seja pregado e ilumina poderosamente as suas mentes pelo Espírito Santo de sorte que possam compreender e discernir corretamente as coisas do Espírito de Deus. Pela operação eficaz do mesmo Espírito regenerador, Ele também penetra até os recantos mais íntimos do homem, abre os corações fechados e abranda os endurecidos, circuncida o que era incircunciso e infunde novas qualidades na vontade: faz viver a vontade outrora morta; a que era má, converte em boa; a indisposta, em solícita; a rebelde, em obediente. Ele muda e fortalece de tal maneira essa vontade que, assim como uma árvore boa, seja capaz de produzir o fruto das boas obras.",
    ],
    refs: "Hb 6.4, 5; 1Co 2.10-14; Hb 4.12; At 16.14; Dt 30.6; Ez 11.19; 36.26; Mt 7.18",
  },
  {
    head: "III/IV",
    number: 12,
    title: "A regeneração é obra de Deus somente",
    paragraphs: [
      "Esta conversão é aquela regeneração, nova criação, ressurgir dos mortos, vivificação, tão exaltada nas Escrituras, a qual Deus opera em nós a despeito de nós. Essa regeneração, contudo, não se realiza de modo algum pelo ensino exterior, pela persuasão moral ou por um modo tal de operação que, após ter Deus feito a Sua parte, fica a critério do homem o regenerar-se ou não, o converter-se ou não. É, portanto, claramente uma obra sobrenatural, poderosíssima, e ao mesmo tempo a mais deleitosa, maravilhosa, misteriosa e indizível. Segundo a Escritura, inspirada pelo Autor dessa obra, a regeneração não é inferior em poder à criação ou à ressurreição dos mortos. Por essa razão todos aqueles em cujos corações Deus opera desse modo maravilhoso são com certeza, infalível e eficazmente regenerados e creem de fato. A vontade assim restaurada não é apenas alvo da ação e da restauração de Deus, mas, sob o agir de Deus, ela também age. Assim, por essa causa, diz-se com justiça que o homem crê e se arrepende mediante a graça que recebeu.",
    ],
    refs: "Jo 3.3; 2Co 4.6; 5:17; Ef 5.14; Jo 5.25; Rm 4.17; Fp 2.13",
  },
  {
    head: "III/IV",
    number: 13,
    title: "A regeneração é incompreensível",
    paragraphs: [
      "Na vida presente, não é possível aos que creem compreenderem totalmente o modo como Deus realiza esta obra. Contudo, lhes é suficiente conhecer e sentir que por essa graça de Deus eles creem de coração e amam o Seu Salvador.",
    ],
    refs: "Jo 3.8; Rm 10.9",
  },
  {
    head: "III/IV",
    number: 14,
    title: "Fé: um dom de Deus",
    paragraphs: [
      "A fé, portanto, é um dom de Deus, não porque é apenas oferecida por Deus ao livre-arbítrio do homem, mas porque é de fato conferida ao homem, implantada e infundida nele. Também não é um dom no sentido de que Deus confere apenas a capacidade para crer, e aguarda do livre-arbítrio do homem a autorização para crer ou o ato de crer. É, antes, um dom no sentido de que é Ele quem efetua no homem tanto o querer quanto o realizar; quem verdadeiramente faz tudo em todos; quem realiza no homem tanto a vontade de crer quanto o ato de crer.",
    ],
    refs: "Ef 2.8; Fp 3.13",
  },
  {
    head: "III/IV",
    number: 15,
    title: "A atitude correta quanto à graça imerecida de Deus",
    paragraphs: [
      "Deus não deve tal graça a ninguém. O que poderia Deus dever ao homem? Quem foi que primeiro deu a Ele, para ser por Ele ressarcido? Que poderia Deus dever a quem nada tem, a não ser pecado e falsidade? Portanto, aquele que recebe essa graça deve e rende eternamente ação de graças somente a Deus. Mas quem não recebe essa graça, não tem o menor interesse por essas coisas espirituais e está satisfeito com o que possui, ou ufana-se com falsa segurança de ter aquilo que não possui. Além disso, quanto aos que professam externamente a sua fé e corrigem as suas vidas devemos julgar e falar da forma mais favorável, segundo o exemplo dos apóstolos, pois não conhecemos o íntimo recôndito do coração; quanto aos que ainda não foram chamados, devemos orar a Deus em favor deles - pois Deus é quem chama à existência às coisas que não existem; quanto a nós, não devemos jamais nos vangloriar, como se nos colocássemos acima dos outros.",
    ],
    refs: "Rm 11.35; Am 6.1; Jr 7.4; Rm 14.10; 4:17; 1Co 4.7",
  },
  {
    head: "III/IV",
    number: 16,
    title: "A vontade do homem não é eliminada, mas é vivificada",
    paragraphs: [
      "O homem, pela sua queda, não deixou de ser homem dotado de inteligência e vontade. O pecado que impregnou toda a raça humana não privou o homem da sua natureza humana, mas trouxe sobre ele a depravação e a morte espiritual. Assim também a graça divina da regeneração não atua sobre os homens como se fossem máquinas ou robôs; não elimina a vontade e as suas propriedades, nem a coage violentamente, mas torna-a espiritualmente viva, sara-a, corrige-a e, a um só tempo agradável e poderosamente, submete-a. O resultado é que onde antes dominava totalmente a rebelião e a resistência da carne, agora, pelo Espírito, começa a prevalecer uma pronta e sincera obediência, que é a verdadeira renovação e libertação espiritual da nossa vontade. E se o Maravilhoso Autor de todo o bem não tivesse nos conduzido dessa maneira, o homem não teria a menor esperança de erguer-se da sua queda mediante o seu livre-arbítrio, o qual, quando ela ainda estava de pé, o lançou na perdição.",
    ],
    refs: "Rm 8.2; Ef 2.1; Sl 51.12; Fp 2.13",
  },
  {
    head: "III/IV",
    number: 17,
    title: "O uso dos meios",
    paragraphs: [
      "A ação onipotente de Deus pela qual Ele produz e sustenta a nossa vida natural, não exclui, antes requer, o uso de meios através dos quais Ele quis exercer o Seu poder, segundo a Sua infinita sabedoria e bondade. Assim também a mencionada ação sobrenatural de Deus mediante a qual Ele nos regenera, não exclui nem cancela de jeito nenhum o uso do Evangelho que o sapientíssimo Deus ordenou para ser a semente da regeneração e o alimento da alma. Por esta razão os apóstolos e os mestres que os sucederam ensinaram reverentemente ao povo sobre a graça de Deus, para a glória dEle e para a vergonha de toda a soberba. Ao mesmo tempo não descuidaram de guardar o povo por meio das santas admoestações do Evangelho, debaixo da administração da Palavra, dos sacramentos e da disciplina. Portanto, os que hoje instruem ou são instruídos na igreja não devem ousar tentar a Deus separando aquilo que Ele pelo Seu beneplácito quis unir inseparavelmente. Assim, a graça é concedida mediante admoestações, e quanto mais prontamente cumprirmos com o nosso dever, tanto mais esse favor de Deus, que é quem opera em nós, manifesta-se naturalmente em sua glória fazendo a Sua obra prosperar da melhor maneira. A Deus somente seja dada a glória eternamente, tanto pelos meios quanto pelos seus frutos e eficácia da salvação. Amém.",
    ],
    refs: "Is 55.10, 11; 1Co 1.21; Tg 1.18; 1Pe 1.23, 25; 2.2; At 2.42; 2Co 5.11-21; 2Tm 4.2; Rm 10.14-17; Jd 24, 25",
  },
  {
    head: "V",
    number: 1,
    title: "Os regenerados não estão livres do pecado interior",
    paragraphs: [
      "Aqueles que, de acordo com o seu propósito, Deus chama à comunhão do Seu Filho, nosso Senhor Jesus Cristo, e regenera pelo Seu Espírito Santo, Ele certamente os livra do domínio e da escravidão do pecado. Mas nesta vida, Ele não os livra totalmente da carne e do corpo do pecado.",
    ],
    refs: "Jo 8.34; Rm 6.17; 7.21-24",
  },
  {
    head: "V",
    number: 2,
    title: "Os pecados diários da fraqueza",
    paragraphs: [
      "Por essa causa ocorrem os pecados diários das fraquezas e há imperfeições até mesmo nas melhores obras dos santos. Para eles essas coisas são motivo permanente para se humilharem diante de Deus, para se refugiarem no Cristo crucificado, para mortificarem a carne cada vez mais mediante o Espírito de oração e através de santos exercícios de piedade, e para ansiarem e se esforçarem pelo alvo da perfeição até que finalmente, livres do corpo dessa morte, reinem com o Cordeiro de Deus no céu.",
    ],
    refs: "1Jo 1.8; Cl 3.5; 1Tm 4.7; Fp 3.12, 14; Ap 5.6, 10",
  },
  {
    head: "V",
    number: 3,
    title: "Deus preserva os que são Seus",
    paragraphs: [
      "Por causa desses resquícios do pecado que ainda restam no íntimo e também por causa das tentações do mundo e de Satanás, os convertidos não conseguiriam perseverar nessa graça se deixados às suas próprias forças. Mas Deus é fiel e os confirma misericordiosamente na graça que, de uma vez por todas, lhes foi outorgada e os preserva poderosamente nela até o fim.",
    ],
    refs: "Rm 7.20; 1Co 10.13; 1Pe 1.5",
  },
  {
    head: "V",
    number: 4,
    title: "Os santos estão sujeitos a cair em pecados graves",
    paragraphs: [
      "Embora o poder de Deus, pelo qual Ele confirma e preserva os verdadeiros crentes na graça, seja tão grande que não pode ser vencido pela carne, os convertidos, contudo, nem sempre são guiados e dirigidos por Deus de sorte que não possam, em certas circunstâncias particulares e pela própria culpa deles, se desviar da direção da graça e serem seduzidos pela carne e se rendam à sua concupiscência. Por isso eles devem orar e vigiar constantemente para que não caiam em tentação. Quando não vigiam nem oram, eles não somente podem ser levados pela carne, pelo mundo e por Satanás - a cometer sérios e atrozes pecados, mas, algumas vezes, podem ser levados a isso pela justa permissão de Deus. É o que demonstra a lastimável queda de Davi, de Pedro e de outros santos, descritas nas Escrituras.",
    ],
    refs: "Ef 1.19; Mt 26.41; 1Ts 5.6, 17; 2Sm 11; Mt 26",
  },
  {
    head: "V",
    number: 5,
    title: "As consequências desses graves pecados",
    paragraphs: [
      "Eles, no entanto, por causa desses pecados grosseiros ofendem profundamente a Deus, tornam-se culpados de morte, entristecem o Espírito Santo, suspendem o exercício da fé, ferem gravamente as suas consciências, e algumas vezes perdem o senso do favor de Deus - até que voltem ao reto caminho sinceramente arrependidos e a face paternal de Deus volte a brilhar sobre eles.",
    ],
    refs: "2Sm 12; Ef 4.30; Sl 32.3-5; Nm 6.25",
  },
  {
    head: "V",
    number: 6,
    title: "Deus não permitirá que os Seus eleitos se percam",
    paragraphs: [
      "Pois Deus, que é rico em misericórdia, segundo o Seu propósito imutável de eleição, não retira completamente o Seu Espírito Santo dos que lhe pertencem, mesmo na sua deplorável queda. Tampouco permite que se afundem tanto a ponto de caírem da graça da adoção e do estado de justificação ou, que cometam o pecado para a morte - isto é, o pecado contra o Espírito Santo - e que, totalmente abandonados por Ele, se lancem na ruína eterna.",
    ],
    refs: "Ef 1.11; 2.4; Sl 51.13; Gl 4.5; 1Jo 5.16-18; Mt 12.31, 32",
  },
  {
    head: "V",
    number: 7,
    title: "Deus renovará os Seus eleitos para o arrependimento",
    paragraphs: [
      "Pois Deus, em primeiro lugar, preserva neles durante a queda, a Sua semente imperecível de regeneração para que ela não morra e seja lançada fora. Além disso, através da Sua Palavra e do Seu Espírito Ele certamente e eficazmente os renova para o arrependimento. O resultado é que se afligem de coração com uma tristeza espiritual pelos pecados que cometeram; buscam e obtêm pela fé, com o coração contrito, o perdão no sangue do Mediador; experimentam novamente o favor de um Deus reconciliado e adoram as Suas misericórdias e fidelidade; daí em diante passam a desenvolver mais diligentemente a própria salvação com temor e tremor.",
    ],
    refs: "1Pe 1.23; 1Jo 3.9; 2Co 7.10; Sl 32.5; 51.19; Fp 2.12",
  },
  {
    head: "V",
    number: 8,
    title: "A graça do triuno Deus preserva",
    paragraphs: [
      "Assim, não é pelos seus próprios méritos ou força, mas pela imerecida misericórdia de Deus, que eles não se desviam totalmente da fé e da graça nem permanecem caídos para se perderem totalmente no final. Quanto a eles, isto facilmente poderia acontecer e aconteceria sem dúvida. Mas quanto a Deus, não há a menor possibilidade de que isso aconteça, pois o Seu conselho não pode ser mudado; a Sua promessa não pode falhar; o chamado segundo o Seu propósito não pode ser revogado; o mérito, a intercessão e a proteção de Cristo não podem ser anuladas; e o selar do Espírito Santo não pode ser frustrado nem destruído.",
    ],
    refs: "Sl 33.11; Hb 6.17; Rm 8.30, 34; 9.11; Lc 22.32; Ef 1.13",
  },
  {
    head: "V",
    number: 9,
    title: "A certeza dessa preservação",
    paragraphs: [
      "Os próprios crentes podem ter a plena certeza da preservação do eleito para a salvação e da perseverança dos verdadeiros crentes na fé. E estão de fato convictos segundo a medida da fé de cada um deles, pela qual creem firmemente que são e que permanecerão membros verdadeiros e vivos da igreja e que possuem o perdão dos pecados e a vida eterna.",
    ],
    refs: "Rm 8.31-39; 2Tm 4.8, 18",
  },
  {
    head: "V",
    number: 10,
    title: "A fonte dessa certeza",
    paragraphs: [
      "Tal certeza não procede de alguma revelação particular além ou fora da Palavra, mas da fé nas promessas de Deus, que Ele revelou abundantemente em Sua Palavra para a nossa consolação; procede do testemunho do Espírito Santo que testifica com o nosso espírito que somos filhos e herdeiros de Deus; e finalmente, da busca incessante e séria por uma consciência limpa e de boas obras. Se os eleitos de Deus não tivessem neste mundo a sólida consolação da obtenção da vitória e da garantia infalível da glória eterna, eles seriam os mais miseráveis de todos os homens.",
    ],
    refs: "Rm 8.16-17; 1Jo 3.1, 2; At 24.16; Rm 8.37; 1Co 15.19",
  },
  {
    head: "V",
    number: 11,
    title: "Nem sempre se sente esta certeza",
    paragraphs: [
      "A Escritura, no entanto, testifica que os crentes enquanto nessa vida têm que lutar contra várias dúvidas da carne e, sujeitos a fortes tentações, nem sempre sentem essa segurança da fé nem a certeza da perseverança. Mas Deus, que é o Pai de toda a consolação, não permitirá que sejam tentados além das suas forças, mas com a tentação proverá também o meio de escape, e pelo Espírito Santo fará ressurgir neles a certeza da perseverança.",
    ],
    refs: "2Co 1.3; 1Co 10.13",
  },
  {
    head: "V",
    number: 12,
    title: "Esta certeza é um estímulo à piedade",
    paragraphs: [
      "Esta certeza de perseverança, longe de tornar os crentes verdadeiros em orgulhosos e acomodados, é antes a verdadeira raiz da humildade, da reverência filial, da piedade genuína, da resistência em todo combate, das orações fervorosas, da perseverança no sofrimento e na confissão da verdade, e da duradoura alegria em Deus. Além disso, a reflexão sobre esses benefício é para eles um incentivo à séria e constante prática da gratidão e das boas-obras, como evidencia o testemunho da Escritura e os exemplos dos santos.",
    ],
    refs: "Rm 12.1; Sl 56.12, 13; 116.12; Tt 2.11-14; 1Jo 3.3",
  },
  {
    head: "V",
    number: 13,
    title: "Esta certeza não leva à negligência",
    paragraphs: [
      "A confiança renovada não leva aqueles que foram restaurados, depois de haverem caído, à falta de zelo nem à negligência da piedade; antes produz neles um cuidado ainda maior em observar os caminhos do Senhor, que Ele preparou de antemão. Eles guardam esses caminhos para que ao andar neles conservem a certeza da sua própria perseverança; para que a face do seu Deus gracioso não se retire deles mais uma vez, por abusarem da Sua bondade paternal; para não caírem em maior angústia espiritual. De fato, para os que temem a Deus a contemplação da Sua face é mais doce do que a vida, e o privar-se dela é mais amargo do que a morte.",
    ],
    refs: "2Co 7.10; Ef 2.10; Sl 63.4; Is 64.7; Jr 33.5",
  },
  {
    head: "V",
    number: 14,
    title: "O uso dos meios de graça na perseverança",
    paragraphs: [
      "Assim como aprouve a Deus começar essa obra de graça em nós pela pregação do Evangelho, assim Ele a mantém, Ele a continua e Ele a aperfeiçoa em nós pelo ouvir e pela leitura da Sua Palavra, pela meditação nela, pelas suas exortações, ameaças e promessas, e pelo uso dos sacramentos.",
    ],
    refs: "Dt 6.20-25; 2Tm 3.16, 17; At 2.42",
  },
  {
    head: "V",
    number: 15,
    title: "Esta doutrina é odiada por Satanás, mas é amada pela igreja",
    paragraphs: [
      "Esta doutrina da perseverança dos verdadeiros crentes e santos, assim como a convicção que têm dela, Deus revelou abundantemente em Sua Palavra para a glória do Seu nome e consolação dos piedosos. Ele é quem a imprime nos corações dos crentes. É algo que a carne não compreende, que Satanás odeia, que o mundo zomba, que os ignorantes e os hipócritas ultrajam e que os heréticos atacam. A Noiva de Cristo, por outro lado, sempre amou mui ternamente esta doutrina e sempre a defendeu firmemente como a um tesouro de valor inestimável; e Deus, contra quem não vale conselho nem força alguma prevalece, cuidará para que ela continue a fazer assim. A esse Deus somente - Pai, Filho e Espírito Santo - seja a honra e a glória para sempre. Amém.",
    ],
    refs: "Ap 14.12; Ef 5.32; Sl 33.10, 11; 1Pe 5.10, 11",
  },
]
